In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import glob
import re

ruta = "/content/drive/MyDrive/ProyectoAnálisis/*.csv"
files = glob.glob(ruta)

dataframes = []

for file in files:
    df = pd.read_csv(file)

    # extraer año del nombre del archivo
    year = re.search(r'\d{4}', file).group()
    df["year"] = int(year)

    dataframes.append(df)

print(f"Se cargaron {len(dataframes)} datasets.")

/tmp/ipykernel_266/1518428597.py:11: DtypeWarning: Columns (104) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_266/1518428597.py:11: DtypeWarning: Columns (104) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_266/1518428597.py:11: DtypeWarning: Columns (81,82,83,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_266/1518428597.py:11: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Se cargaron 10 datasets.

In [3]:
#Busqueda de columnas diferentes
todas_columnas = set()

for df in dataframes:
    todas_columnas.update(df.columns)

print("Total columnas diferentes encontradas:", len(todas_columnas))

for col in sorted(todas_columnas):
    print(col)

Total columnas diferentes encontradas: 159
Acceleration
Age
Aggression
Agility
Att work rate
Balance
Ball
Club
Composure
Crossing
Curve
Def
Def work rate
Defending
Dribbling
Finishing
Free
GK
Gender
Heading
Interceptions
Jumping
Long
Name
Nation
Overall
Pace
Passing
Penalties
Physicality
Position
Positioning
Preferred foot
Reactions
Shooting
Shot
Skill moves
Sliding
Sprint
Stamina
Standing
Strength
URL
Unnamed: 0
Vision
Volleys
Weak foot
Year
age
attacking_crossing
attacking_finishing
attacking_heading_accuracy
attacking_short_passing
attacking_volleys
body_type
cam
cb
cdm
cf
club_contract_valid_until
club_flag_url
club_jersey_number
club_joined
club_loaned_from
club_logo_url
club_name
club_position
club_team_id
cm
defending
defending_marking_awareness
defending_sliding_tackle
defending_standing_tackle
dob
dribbling
gk
goalkeeping_diving
goalkeeping_handling
goalkeeping_kicking
goalkeeping_positioning
goalkeeping_reflexes
goalkeeping_speed
height_cm
international_reputation
lam
lb
lcb
lcm
ldm
league_level
league_name
lf
lm
long_name
ls
lw
lwb
mentality_aggression
mentality_composure
mentality_interceptions
mentality_penalties
mentality_positioning
mentality_vision
movement_acceleration
movement_agility
movement_balance
movement_reactions
movement_sprint_speed
nation_flag_url
nation_jersey_number
nation_logo_url
nation_position
nation_team_id
nationality_id
nationality_name
overall
pace
passing
physic
player_face_url
player_positions
player_tags
player_traits
player_url
potential
power_jumping
power_long_shots
power_shot_power
power_stamina
power_strength
preferred_foot
ram
rb
rcb
rcm
rdm
real_face
release_clause_eur
rf
rm
rs
rw
rwb
shooting
short_name
skill_ball_control
skill_curve
skill_dribbling
skill_fk_accuracy
skill_long_passing
skill_moves
sofifa_id
st
value_eur
wage_eur
weak_foot
weight_kg
work_rate
year

In [8]:
for df in dataframes:
    print("year:", df["year"].iloc[0])
    print(len(df.columns), "columnas")
    print(df.columns.tolist())
    print()

year: 2015
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2016
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2017
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2018
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2019
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2020
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2021
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2022
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2024
48 columnas
['Unnamed: 0', 'Name', 'Nation', 'Club', 'Position', 'Age', 'Overall', 'Pace', 'Shooting', 'Passing', 'Dribbling', 'Defending', 'Physicality', 'Acceleration', 'Sprint', 'Positioning', 'Finishing', 'Shot', 'Long', 'Volleys', 'Penalties', 'Vision', 'Crossing', 'Free', 'Curve', 'Agility', 'Balance', 'Reactions', 'Ball', 'Composure', 'Interceptions', 'Heading', 'Def', 'Standing', 'Sliding', 'Jumping', 'Stamina', 'Strength', 'Aggression', 'Att work rate', 'Def work rate', 'Preferred foot', 'Weak foot', 'Skill moves', 'URL', 'Gender', 'GK', 'year']

year: 2023
26 columnas
['Name', 'Position', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'height_cm', 'weight_kg', 'league_name', 'league_level', 'Club', 'Nation', 'preferred_foot', 'weak_foot', 'skill_moves', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'Physicality', 'movement_acceleration', 'movement_sprint_speed', 'power_stamina', 'year']

In [7]:
for i in range(len(dataframes)):
  # Check if the 'Year' column exists in the current dataframe
  if "Year" in dataframes[i].columns:
    # If it exists, drop it and update the dataframe in the list
    dataframes[i] = dataframes[i].drop(columns=["Year"])

In [9]:
#Renombrado de columnas
rename_dict = {

# nombres
"short_name": "name",
"Name": "name",

# posición
"player_positions": "position",
"Position": "position",

# overall
"Overall": "overall",

# club
"club_name": "club",
"Club": "club",

# nación
"nationality_name": "nation",
"Nation": "nation",

# físico
"physic": "physicality",
"Physicality": "physicality",

# edad
"Age": "age",

# pace
"Pace": "pace",

# shooting
"Shooting": "shooting",

# passing
"Passing": "passing",

# dribbling
"Dribbling": "dribbling",

# defending
"Defending": "defending",

# weak foot
"Weak foot": "weak_foot",

# preferred foot
"Preferred foot": "preferred_foot",

# skill moves
"Skill moves": "skill_moves",

# aceleración
"Acceleration": "movement_acceleration",

# sprint
"Sprint": "movement_sprint_speed",

# stamina
"Stamina": "power_stamina",

# year
"Year": "year"
}

for i in range(len(dataframes)):
    dataframes[i] = dataframes[i].rename(columns=rename_dict)

In [10]:
#Selección de columnas finales para cada .csv
columnas_finales = [
"name",
"position",
"overall",
"potential",
"value_eur",
"wage_eur",
"age",
"height_cm",
"weight_kg",
"league_name",
"league_level",
"club",
"nation",
"preferred_foot",
"weak_foot",
"skill_moves",
"pace",
"shooting",
"passing",
"dribbling",
"defending",
"physicality",
"movement_acceleration",
"movement_sprint_speed",
"power_stamina",
"year"
]

for df in dataframes:

    y = df["year"].iloc[0]

    faltantes = [c for c in columnas_finales if c not in df.columns]

    if faltantes:
        print(f"Año {y} le faltan columnas:")
        print(faltantes)
        print()

Año 2024 le faltan columnas:
['potential', 'value_eur', 'wage_eur', 'height_cm', 'weight_kg', 'league_name', 'league_level']

In [11]:
#Colocar las columnas faltantes y rellenarlo de nulos

for i in range(len(dataframes)):

    for col in columnas_finales:
        if col not in dataframes[i].columns:
            dataframes[i][col] = pd.NA

In [12]:
#Seleccionar solo las columnas finales para cada .csv
for i in range(len(dataframes)):
    dataframes[i] = dataframes[i][columnas_finales]

In [ ]:
#Impurnar datos al 2024
#Limpieza nulos y duplicados
#Agregar columna de region con chat

In [13]:
#Unir los 9 csv
df_total = pd.concat(dataframes, ignore_index=True)

print("Shape del dataset final:", df_total.shape)

df_total.info()

df_total.head()

/tmp/ipykernel_266/3899444425.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_total = pd.concat(dataframes, ignore_index=True)

Shape del dataset final: (324598, 26)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324598 entries, 0 to 324597
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   name                   324598 non-null  object
 1   position               324598 non-null  object
 2   overall                324598 non-null  int64
 3   potential              308753 non-null  object
 4   value_eur              306036 non-null  float64
 5   wage_eur               306405 non-null  float64
 6   age                    324598 non-null  int64
 7   height_cm              308753 non-null  object
 8   weight_kg              308753 non-null  object
 9   league_name            306397 non-null  object
 10  league_level           306012 non-null  float64
 11  club                   322242 non-null  object
 12  nation                 324598 non-null  object
 13  preferred_foot         324598 non-null  object
 14  weak_foot              324598 non-null  int64
 15  skill_moves            324598 non-null  int64
 16  pace                   290201 non-null  float64
 17  shooting               290201 non-null  float64
 18  passing                290201 non-null  float64
 19  dribbling              290201 non-null  float64
 20  defending              290201 non-null  float64
 21  physicality            290201 non-null  float64
 22  movement_acceleration  324598 non-null  int64
 23  movement_sprint_speed  324598 non-null  int64
 24  power_stamina          324598 non-null  int64
 25  year                   324598 non-null  int64
dtypes: float64(9), int64(8), object(9)
memory usage: 64.4+ MB

,name,position,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,league_name,...,pace,shooting,passing,dribbling,defending,physicality,movement_acceleration,movement_sprint_speed,power_stamina,year
0,L. Messi,CF,93,95,100500000.0,550000.0,27,169,67,Spain Primera Division,...,93.0,89.0,86.0,96.0,27.0,63.0,96,90,77,2015
1,Cristiano Ronaldo,"LW, LM",92,92,79000000.0,375000.0,29,185,80,Spain Primera Division,...,93.0,93.0,81.0,91.0,32.0,79.0,91,94,89,2015
2,A. Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,180,80,German 1. Bundesliga,...,93.0,86.0,83.0,92.0,32.0,64.0,93,93,78,2015
3,Z. Ibrahimović,ST,90,90,52500000.0,275000.0,32,195,95,French Ligue 1,...,76.0,91.0,81.0,86.0,34.0,86.0,74,77,78,2015
4,M. Neuer,GK,90,90,63500000.0,300000.0,28,193,92,German 1. Bundesliga,...,NaN,NaN,NaN,NaN,NaN,NaN,58,61,44,2015

In [14]:
#Tipado

# columnas categóricas
categoricas = [
"name",
"position",
"league_name",
"club",
"nation",
"preferred_foot"
]

# columnas enteras
enteras = [
"overall",
"potential",
"age",
"height_cm",
"weight_kg",
"weak_foot",
"skill_moves",
"pace",
"shooting",
"passing",
"dribbling",
"defending",
"physicality",
"movement_acceleration",
"movement_sprint_speed",
"power_stamina",
"league_level",
"year"
]

# columnas float
floats = [
"value_eur",
"wage_eur"
]

# aplicar tipado
df_total[categoricas] = df_total[categoricas].astype("category")
df_total[enteras] = df_total[enteras].astype("Int64")
df_total[floats] = df_total[floats].astype("float")

df_total.dtypes

name                     category
position                 category
overall                     Int64
potential                   Int64
value_eur                 float64
wage_eur                  float64
age                         Int64
height_cm                   Int64
weight_kg                   Int64
league_name              category
league_level                Int64
club                     category
nation                   category
preferred_foot           category
weak_foot                   Int64
skill_moves                 Int64
pace                        Int64
shooting                    Int64
passing                     Int64
dribbling                   Int64
defending                   Int64
physicality                 Int64
movement_acceleration       Int64
movement_sprint_speed       Int64
power_stamina               Int64
year                        Int64
dtype: object

In [15]:
#Busqueda de nulos
nulos = df_total.isnull().sum()
print(nulos)

porcentaje_nulos = (df_total.isnull().sum() / len(df_total)) * 100

print(porcentaje_nulos.sort_values(ascending=False))

name                         0
position                     0
overall                      0
potential                15845
value_eur                18562
wage_eur                 18193
age                          0
height_cm                15845
weight_kg                15845
league_name              18201
league_level             18586
club                      2356
nation                       0
preferred_foot               0
weak_foot                    0
skill_moves                  0
pace                     34397
shooting                 34397
passing                  34397
dribbling                34397
defending                34397
physicality              34397
movement_acceleration        0
movement_sprint_speed        0
power_stamina                0
year                         0
dtype: int64
shooting                 10.596800
pace                     10.596800
passing                  10.596800
dribbling                10.596800
defending                10.596800
physicality              10.596800
league_level              5.725852
value_eur                 5.718458
league_name               5.607243
wage_eur                  5.604779
potential                 4.881423
weight_kg                 4.881423
height_cm                 4.881423
club                      0.725821
age                       0.000000
overall                   0.000000
name                      0.000000
position                  0.000000
weak_foot                 0.000000
skill_moves               0.000000
nation                    0.000000
preferred_foot            0.000000
movement_acceleration     0.000000
movement_sprint_speed     0.000000
power_stamina             0.000000
year                      0.000000
dtype: float64

In [16]:
#Reporte de nulos
reporte_nulos = pd.DataFrame({
    "columna": df_total.columns,
    "nulos": df_total.isnull().sum(),
    "porcentaje": (df_total.isnull().sum() / len(df_total)) * 100
})

reporte_nulos = reporte_nulos.sort_values("porcentaje", ascending=False)

reporte_nulos

                                     columna  nulos  porcentaje
shooting                            shooting  34397   10.596800
pace                                    pace  34397   10.596800
passing                              passing  34397   10.596800
dribbling                          dribbling  34397   10.596800
defending                          defending  34397   10.596800
physicality                      physicality  34397   10.596800
league_level                    league_level  18586    5.725852
value_eur                          value_eur  18562    5.718458
league_name                      league_name  18201    5.607243
wage_eur                            wage_eur  18193    5.604779
potential                          potential  15845    4.881423
weight_kg                          weight_kg  15845    4.881423
height_cm                          height_cm  15845    4.881423
club                                    club   2356    0.725821
age                                      age      0    0.000000
overall                              overall      0    0.000000
name                                    name      0    0.000000
position                            position      0    0.000000
weak_foot                          weak_foot      0    0.000000
skill_moves                      skill_moves      0    0.000000
nation                                nation      0    0.000000
preferred_foot                preferred_foot      0    0.000000
movement_acceleration  movement_acceleration      0    0.000000
movement_sprint_speed  movement_sprint_speed      0    0.000000
power_stamina                  power_stamina      0    0.000000
year                                    year      0    0.000000

In [17]:
#Busqueda de duplicados
duplicados = df_total.duplicated().sum()

print("Filas duplicadas:", duplicados)

porcentaje_dup = (duplicados / len(df_total)) * 100

print("Porcentaje duplicados:", porcentaje_dup, "%")

Filas duplicadas: 124635
Porcentaje duplicados: 38.39672456392214 %